### PR TITLE
Development alpha 

### PR DESCRIPTION
**Pull request by imhta**
[Preview](https://the-next-web-clone.imhta.now.sh)

### CODE REVIEW

**Comment by HenryTabima** [comment]
# Awesome :tada:
Hey! Great job with this project :clap:. Good use of semantic HTML, you're on the right path :runner:. Just some changes before you get thumbs up on this project:

To consider the project 'complete' it must satisfy the following points:

## Project Specification Shortcut

### Mobile [Up to 480px]
- [x] The CSS files should have a media query that displays the content up to 480px screen size

#### Navigation bar
- [x] It should use fixed positioning

#### Latest Funding section
- [x] It should have three articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Apps section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Arrangement of Gear section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Tech section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Creative section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Podium section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Insight section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Lunch and Distract section
- [x] It should be wrapped around a pair of `<section>` HTML tags
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%

#### Latest Deals section
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 100%


### Medium [768px to 1024px]
- [x] The CSS files should have a media query that displays the content from 768px to 1024px

#### Main content

##### Latest Deals section
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with width and height values set to 33%
- [x] Each article should have an image with its width property set to 100% and the height property set to 60% as well as a title with a width property set to 100% and the height set to 40%

### Large [1024px and up]
- [x] The CSS files should have a media query that displays the content from 1024px and up

#### Main content

##### Latest News section
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags witt the width property set to 25% and the height set to 33%
- [x] Each article should have an image with its width property set to 100% and the height property set to 60% as well as a title with a width property set to 100% and the height set to 40%

##### Latest funding section
- [x] Each article should have an image on the leftmost part of the article and its title on the right side
- [x] It should have eight articles, each one wrapped around a pair of `<article>` HTML tags with a width value set to 25%

**Comment by imhta** [comment]
kindly give the reasoning for your claim, we fixed the requested claim.

**Comment by HenryTabima** [comment]
Hello there. You have done excellent work with this project. the claims were just the guidelines we have to follow as TSE.

**Comment by HenryTabima** [comment]
# Great job :tada: 
This is a thumbs up :+1: for me, you can continue submitting your project completion form and go ahead with the next project.

**Comment by imhta** [comment]
Thank you

**Pull request merged**
